import React, { useState } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Menu from '../pages/Menu';
import Top from './Components/header';
import { Container, Row, Col, Alert } from 'reactstrap';

export default function Home(props,) {
  const [wid, setWid] = useState('25%');
  
    const closeMenu = () => {
      setWid('0%');
    } 

    const openMenu = () => {
      setWid('25%');
    }

  return (
    <div className={styles.main}>
      {/* https://github.com/vercel/styled-jsx#via-interpolated-dynamic-props */}
      <style jsx global>{ `body { 
        background: #e0e1e2; 
        overflow: hidden;
        }`} 
      </style>
      <Head>
        <title>Get SWFT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Top />
      <main> 
        <div className="container">
         <div className="row g-0" className={styles.dash_top}>
            <div className="col" >
              <div className="justify-content-center align-items-center" id={styles.menu}>
                <button onClick={openMenu}>OPEN MENU</button>
                <Menu width={wid} closeNav={closeMenu}/>
              </div>
            </div>
            <div className="col">
              <div className="row g-0">
                <div className="col">
                  <div className={styles.dash_waiting}>
                    <div className={styles.dash_waiting_text}>
                      24
                    </div>
                    WAITING CANDIDATES
                  </div>
                </div>
               
                <div className="col">
                  <div className={styles.dash_waiting_white}>
                    <div className={styles.dash_waiting_text}>
                      100
                    </div>
                    TOTAL APPLIED
                    </div>
                </div>

                <div className="col">
                  <div className={styles.dash_waiting_white}>
                    <div className={styles.dash_waiting_text}>
                      100
                    </div>
                    TOTAL SWIPED
                    </div>
                </div>
             

                <div className="col">
                  <div className={styles.dash_waiting_white}>
                    <div className={styles.dash_waiting_text}>
                      5
                    </div>
                    ACTIVE REQS
                    </div>
                </div>

              </div>
            </div>

            <div className="container">
              <div className="row">
                <div className="col">
                  <div className={styles.calendar}>
                    CALENDAR
                  </div>
                </div>
                <div className="col">
                <div className={styles.calendar}>
                    CALENDAR
                  </div>
                </div>
              </div>
            </div>
            
              {/* <div className="row">
                <div className="col-3">CALENDAR</div>
                <div className="col-3">LIKED/INCLINED</div>
                <div className="col-3">DEMOGRATPHIC STATS</div>
              </div>
              <div className="row">
                <div className="col">GRAPH</div>
              </div> */}

         </div>
         </div>
    
      </main>


    </div>
  )
}
