import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Menu from '../pages/Menu';
import Top from './Components/header';
import { Container, Row, Col } from 'reactstrap';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Get</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Top />
      <main>
       <Container>
         <Row>
            <Col xs={2}>MENU</Col>
            <Col xs={10}>
              <Row>
                <Col>WAITING CANDIDATES</Col>
                <Col>TOTAL APPLIED</Col>
                <Col>TOTAL SWIPED</Col>
                <Col>ACTIVE REQS</Col>
              </Row>
              <Row>
                <Col>CALENDAR</Col>
                <Col>LIKED/INCLINED</Col>
                <Col>DEMOGRATPHIC STATS</Col>
              </Row>
              <Row>
                <Col>GRAPH</Col>
              </Row>
            </Col>

         </Row>
       </Container>
      </main>


    </div>
  )
}
