import React, { useState } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Menu from '../pages/Menu';
import Top from './Components/header';
import { Container, Row, Col, Alert } from 'reactstrap';

export default function Home(props,) {
  const [wid, setWid] = useState('25%');
  
    const closeMenu = () => {
      setWid('0%');
    } 

    const openMenu = () => {
      setWid('25%');
    }

  return (
    <div className={styles.main}>
      {/* https://github.com/vercel/styled-jsx#via-interpolated-dynamic-props */}
      <style jsx global>{ `body { 
        background: #e0e1e2; 
        overflow: hidden;
        }`} 
      </style>
      <Head>
        <title>Get SWFT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Top />
      <main> 
        <button onClick={openMenu}>OPEN MENU</button>
        <Menu width={wid} closeNav={closeMenu}/>



         <Row className={styles.dash_top}>
            <Col xs={3} className="justify-content-center align-items-center" id={styles.dash_menu}>
              test
            </Col>
            <Col xs={9}>
              <Row>
                <Col xs={3}>
                  <div className={styles.dash_waiting}>
                  WAITING CANDIDATES
                  </div>
                </Col>
                <Col xs={3}>TOTAL APPLIED</Col>
                <Col xs={3}>TOTAL SWIPED</Col>
                <Col xs={3}>ACTIVE REQS</Col>
              </Row>
              <Row>
                <Col>CALENDAR</Col>
                <Col>LIKED/INCLINED</Col>
                <Col>DEMOGRATPHIC STATS</Col>
              </Row>
              <Row>
                <Col>GRAPH</Col>
              </Row>
            </Col>

         </Row>
    
      </main>


    </div>
  )
}
